// <auto-generated />
namespace CafeStatus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PushDevice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PushDevice));
        
        string IMigrationMetadata.Id
        {
            get { return "201604291540282_PushDevice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
